### ISSUE TITLE
出不去新手村啊

### ISSUE THREAD

**Issue by daoBrother** [ByteLegendQuest/remember-brave-people#137]
![image](https://user-images.githubusercontent.com/90307768/132480645-580b3a27-6f9e-471d-9542-70f065abef90.png)
你好！请问我每次提交都会遇到这个问题，能帮忙解决一下嘛

**Comment by blindpirate** [comment]
![image](https://user-images.githubusercontent.com/12689835/132481223-dbcd3d76-e441-4e94-a41f-0a676febe6b5.png)

请先解决冲突。不会解决的话，删掉你fork的仓库重来一遍。

**Comment by daoBrother** [comment]
完成以后还是出不了新手村啊，是不是只有新手村啊
