### ISSUE TITLE
I cant update myselt info to json file.

### ISSUE THREAD

**Issue by reallEz** [ByteLegendQuest/remember-brave-people#655]
![image](https://user-images.githubusercontent.com/85923172/139656784-afa404ab-ee37-4c24-b729-60472e72c86e.png)
link: https://github.com/ByteLegendQuest/remember-brave-people/runs/4066543985?check_suite_focus=true
CI tells me that i am trying to modify others info.
But i'm just trying to update myself info...
See PR here:
https://github.com/ByteLegendQuest/remember-brave-people/pull/654

**Comment by blindpirate** [comment]
Try correcting your GitHub username: https://github.com/ByteLegendQuest/remember-brave-people/pull/654/files#r740137480
